# Generated by Django 6.0.2 on 2026-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='has_experience',
            field=models.BooleanField(default=False),
        ),
    ]
