# Generated by Django 6.0.2 on 2026-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('study_work', models.CharField(max_length=255)),
                ('english_level', models.CharField(max_length=100)),
                ('additional_languages', models.CharField(blank=True, max_length=255)),
                ('previous_experience', models.TextField(blank=True)),
                ('why_volunteer', models.TextField()),
                ('cv_file', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
